# Generated by Django 5.2.4 on 2025-07-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=500, verbose_name='Название (русский)')),
                ('title_kk', models.CharField(blank=True, max_length=500, verbose_name='Название (казахский)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Название (английский)')),
                ('abstract_ru', models.TextField(verbose_name='Аннотация (русский)')),
                ('abstract_kk', models.TextField(blank=True, verbose_name='Аннотация (казахский)')),
                ('abstract_en', models.TextField(blank=True, verbose_name='Аннотация (английский)')),
                ('keywords_ru', models.CharField(max_length=500, verbose_name='Ключевые слова (русский)')),
                ('keywords_kk', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова (казахский)')),
                ('keywords_en', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова (английский)')),
                ('page_start', models.PositiveIntegerField(verbose_name='Страница начала')),
                ('page_end', models.PositiveIntegerField(verbose_name='Страница конца')),
                ('pdf_file', models.FileField(upload_to='articles/pdfs/', verbose_name='PDF статьи')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('review', 'На рецензии'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('published', 'Опубликована')], default='draft', max_length=10, verbose_name='Статус')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Загрузки')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Казахский'), ('en', 'Английский')], default='ru', max_length=2, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
