# Generated by Django 5.2.7 on 2025-11-06 06:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        ('issues', '0002_issue_slug_issue_issues_issu_year_6149c4_idx_and_more'),
        ('submissions', '0003_section_remove_submission_abstract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Изображение'), ('supp', 'Дополнительные материалы'), ('other', 'Другое')], db_index=True, default='pdf', max_length=20, verbose_name='Тип файла')),
                ('file', models.FileField(max_length=500, upload_to='articles/files/%Y/%m/%d/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME тип')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Файл статьи',
                'verbose_name_plural': 'Файлы статей',
                'ordering': ['kind', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Казахский'), ('en', 'Английский')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('abstract', models.TextField(verbose_name='Аннотация')),
                ('body_html', models.TextField(blank=True, verbose_name='Полный текст (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Локализация статьи',
                'verbose_name_plural': 'Локализации статей',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200, verbose_name='Термин')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Казахский'), ('en', 'Английский')], db_index=True, max_length=2, verbose_name='Язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='submissions.section', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='articles_ar_slug_452037_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='articles_ar_status_7759bd_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['issue', 'status'], name='articles_ar_issue_i_a0ff60_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['doi'], name='articles_ar_doi_f0d052_idx'),
        ),
        migrations.AddField(
            model_name='articlefile',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='articlelocale',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='keywords', to='articles.article', verbose_name='Статьи'),
        ),
        migrations.AddIndex(
            model_name='articlefile',
            index=models.Index(fields=['article', 'kind'], name='articles_ar_article_210256_idx'),
        ),
        migrations.AddIndex(
            model_name='articlelocale',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'abstract', 'body_html'], name='article_locale_gin_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='articlelocale',
            unique_together={('article', 'language')},
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['term', 'language'], name='articles_ke_term_62998d_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['term'], name='keyword_term_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('term', 'language')},
        ),
    ]
