# Generated by Django 5.2.4 on 2025-07-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Год выпуска журнала', verbose_name='Год')),
                ('number', models.PositiveIntegerField(help_text='Номер выпуска в году', verbose_name='Номер')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (русский)')),
                ('title_kk', models.CharField(blank=True, max_length=255, verbose_name='Название (казахский)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Название (английский)')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='issues/covers/', verbose_name='Обложка')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='issues/pdfs/', verbose_name='PDF выпуска')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архивирован')], default='draft', max_length=10, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Выпуск',
                'verbose_name_plural': 'Выпуски',
                'ordering': ['-year', '-number'],
                'unique_together': {('year', 'number')},
            },
        ),
    ]
