# Generated by Django 5.2.7 on 2025-11-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автоматически генерируется из года и номера', max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['year', 'number'], name='issues_issu_year_6149c4_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['slug'], name='issues_issu_slug_14dbd5_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', 'published_at'], name='issues_issu_status_b31e44_idx'),
        ),
    ]
