# Generated by Django 5.2.7 on 2025-11-02 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('submissions', '0003_section_remove_submission_abstract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_url', models.CharField(max_length=500, unique=True, verbose_name='Старый URL')),
                ('new_path', models.CharField(max_length=500, verbose_name='Новый путь')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Редирект',
                'verbose_name_plural': 'Редиректы',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor_in_chief', 'Главный редактор'), ('deputy_editor', 'Заместитель главного редактора'), ('section_editor', 'Редактор раздела'), ('associate_editor', 'Ассоциированный редактор'), ('copy_editor', 'Редактор-корректор'), ('layout_editor', 'Редактор верстки'), ('production_editor', 'Редактор производства')], max_length=20, verbose_name='Роль')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('bio_ru', models.TextField(blank=True, verbose_name='Биография (русский)')),
                ('bio_kk', models.TextField(blank=True, verbose_name='Биография (казахский)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Биография (английский)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('orcid', models.CharField(blank=True, max_length=19, verbose_name='ORCID')),
                ('affiliation', models.CharField(blank=True, max_length=500, verbose_name='Аффилиация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editors', to='submissions.section', verbose_name='Раздел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Член редакционной коллегии',
                'verbose_name_plural': 'Редакционная коллегия',
                'ordering': ['order', 'role', 'user'],
                'unique_together': {('user', 'role', 'section')},
            },
        ),
    ]
