# Generated by Django 5.2.7 on 2025-11-06 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_redirect_editorialteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Название')),
                ('name_en', models.CharField(blank=True, max_length=500, verbose_name='Название (англ.)')),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Аффилиация',
                'verbose_name_plural': 'Аффилиации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('article', 'Статья'), ('file', 'Файл'), ('issue', 'Выпуск'), ('news', 'Новость')], db_index=True, max_length=20, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='ID объекта')),
                ('kind', models.CharField(choices=[('view', 'Просмотр'), ('download', 'Загрузка'), ('redirect', 'Редирект')], db_index=True, max_length=20, verbose_name='Тип события')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, max_length=500, verbose_name='Referer')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NewsLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Казахский'), ('en', 'Английский')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body_html', models.TextField(verbose_name='Полный текст (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Локализация новости',
                'verbose_name_plural': 'Локализации новостей',
            },
        ),
        migrations.CreateModel(
            name='PageLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Казахский'), ('en', 'Английский')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body_html', models.TextField(verbose_name='Полный текст (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Локализация страницы',
                'verbose_name_plural': 'Локализации страниц',
            },
        ),
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(db_index=True, max_length=1000, verbose_name='URL источника')),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SHA256 хеш')),
                ('data', models.JSONField(default=dict, verbose_name='Данные (JSON)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата получения')),
            ],
            options={
                'verbose_name': 'Сырой документ',
                'verbose_name_plural': 'Сырые документы',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddField(
            model_name='redirect',
            name='http_status',
            field=models.SmallIntegerField(choices=[(301, '301 - Постоянный редирект'), (302, '302 - Временный редирект')], default=301, help_text='301 рекомендуется для SEO', verbose_name='HTTP статус'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Новый путь'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='old_url',
            field=models.URLField(db_index=True, max_length=1000, unique=True, verbose_name='Старый URL'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='redirect',
            index=models.Index(fields=['old_url', 'is_active'], name='core_redire_old_url_0412ee_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliation',
            index=models.Index(fields=['name'], name='core_affili_name_cc96a9_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliation',
            index=models.Index(fields=['country'], name='core_affili_country_038f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['object_type', 'object_id', 'kind'], name='core_event_object__f718cc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp', 'kind'], name='core_event_timesta_c71c7c_idx'),
        ),
        migrations.AddField(
            model_name='newslocale',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='core.news', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='pagelocale',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='core.page', verbose_name='Страница'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['sha256'], name='core_rawdoc_sha256_77c29c_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['source_url', 'fetched_at'], name='core_rawdoc_source__5a95a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newslocale',
            unique_together={('news', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='pagelocale',
            unique_together={('page', 'language')},
        ),
    ]
