# Generated by Django 5.2.4 on 2025-07-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название статьи')),
                ('abstract', models.TextField(verbose_name='Аннотация')),
                ('keywords', models.CharField(max_length=500, verbose_name='Ключевые слова')),
                ('manuscript_file', models.FileField(upload_to='submissions/manuscripts/', verbose_name='Рукопись')),
                ('supplementary_files', models.FileField(blank=True, null=True, upload_to='submissions/supplementary/', verbose_name='Дополнительные файлы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('under_review', 'На рецензии'), ('revision_requested', 'Требуются исправления'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('published', 'Опубликована')], default='draft', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author_comments', models.TextField(blank=True, verbose_name='Комментарии автора')),
                ('editor_comments', models.TextField(blank=True, verbose_name='Комментарии редактора')),
                ('submission_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='ID отправки')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Казахский'), ('en', 'Английский')], default='ru', max_length=2, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправки',
                'ordering': ['-created_at'],
            },
        ),
    ]
