# Generated by Django 5.2.4 on 2025-07-29 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='submissions_as_coauthor', to=settings.AUTH_USER_MODEL, verbose_name='Соавторы'),
        ),
        migrations.AddField(
            model_name='submission',
            name='corresponding_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_as_corresponding', to=settings.AUTH_USER_MODEL, verbose_name='Корреспондирующий автор'),
        ),
    ]
