# Generated by Django 5.2.7 on 2025-11-02 14:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (русский)')),
                ('title_kk', models.CharField(blank=True, max_length=200, verbose_name='Название (казахский)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название (английский)')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('require_review', models.BooleanField(default=True, verbose_name='Требуется рецензирование')),
                ('review_type', models.CharField(choices=[('single', 'Одно рецензирование'), ('double', 'Двойное слепое'), ('open', 'Открытое')], default='double', max_length=20, verbose_name='Тип рецензирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['order', 'title_ru'],
            },
        ),
        migrations.RemoveField(
            model_name='submission',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='supplementary_files',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='title',
        ),
        migrations.AddField(
            model_name='submission',
            name='abstract_en',
            field=models.TextField(blank=True, verbose_name='Аннотация (английский)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='abstract_kk',
            field=models.TextField(blank=True, verbose_name='Аннотация (казахский)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='abstract_ru',
            field=models.TextField(blank=True, default='', verbose_name='Аннотация (русский)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assigned_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный редактор'),
        ),
        migrations.AddField(
            model_name='submission',
            name='conflict_of_interest',
            field=models.TextField(blank=True, verbose_name='Конфликт интересов'),
        ),
        migrations.AddField(
            model_name='submission',
            name='data_availability',
            field=models.TextField(blank=True, verbose_name='Доступность данных'),
        ),
        migrations.AddField(
            model_name='submission',
            name='editor_decision_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата решения редактора'),
        ),
        migrations.AddField(
            model_name='submission',
            name='editor_reviewer_comments',
            field=models.TextField(blank=True, verbose_name='Комментарии редактора рецензенту'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ethics_approval',
            field=models.BooleanField(default=False, verbose_name='Получено этическое одобрение'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ethics_committee',
            field=models.CharField(blank=True, max_length=200, verbose_name='Этический комитет'),
        ),
        migrations.AddField(
            model_name='submission',
            name='funding',
            field=models.CharField(blank=True, max_length=500, verbose_name='Финансирование'),
        ),
        migrations.AddField(
            model_name='submission',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова (английский)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='keywords_kk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова (казахский)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='keywords_ru',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ключевые слова (русский)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней рецензии'),
        ),
        migrations.AddField(
            model_name='submission',
            name='last_revision_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последних исправлений'),
        ),
        migrations.AddField(
            model_name='submission',
            name='methodology',
            field=models.TextField(blank=True, verbose_name='Методология'),
        ),
        migrations.AddField(
            model_name='submission',
            name='parent_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='submissions.submission', verbose_name='Родительская подача'),
        ),
        migrations.AddField(
            model_name='submission',
            name='research_field',
            field=models.CharField(blank=True, max_length=200, verbose_name='Область исследования'),
        ),
        migrations.AddField(
            model_name='submission',
            name='review_type',
            field=models.CharField(choices=[('single', 'Одно рецензирование'), ('double', 'Двойное слепое'), ('open', 'Открытое')], default='double', max_length=20, verbose_name='Тип рецензирования'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('new', 'Новая статья'), ('revision', 'Исправленная версия'), ('resubmission', 'Повторная подача')], default='new', max_length=20, verbose_name='Тип подачи'),
        ),
        migrations.AddField(
            model_name='submission',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название статьи (английский)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='title_kk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название статьи (казахский)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название статьи (русский)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='author_comments',
            field=models.TextField(blank=True, verbose_name='Комментарии автора редактору'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='editor_comments',
            field=models.TextField(blank=True, verbose_name='Комментарии редактора автору'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='manuscript_file',
            field=models.FileField(help_text='Основной файл рукописи (PDF, DOC, DOCX)', upload_to='submissions/manuscripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Рукопись'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена редактору'), ('reviewing', 'На рецензии'), ('in_editing', 'В редактировании'), ('reviewer_assigned', 'Рецензент назначен'), ('review_completed', 'Рецензия завершена'), ('revision_requested', 'Требуются исправления'), ('revision_submitted', 'Исправления отправлены'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('in_production', 'В производстве'), ('scheduled', 'Запланирована к публикации'), ('published', 'Опубликована'), ('declined', 'Отозвана автором')], default='draft', max_length=25, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='submission',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='submissions.section', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'zip', 'jpg', 'png'])], verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('manuscript', 'Рукопись'), ('supplementary', 'Дополнительный файл'), ('data', 'Данные'), ('figure', 'Рисунок'), ('table', 'Таблица'), ('other', 'Другое')], default='manuscript', max_length=20, verbose_name='Тип файла')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submission', verbose_name='Подача')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл подачи',
                'verbose_name_plural': 'Файлы подачи',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('is_corresponding', models.BooleanField(default=False, verbose_name='Корреспондирующий автор')),
                ('is_principal', models.BooleanField(default=False, verbose_name='Главный автор')),
                ('affiliation', models.CharField(blank=True, max_length=500, verbose_name='Аффилиация')),
                ('orcid', models.CharField(blank=True, max_length=19, verbose_name='ORCID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_authorships', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_authors', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Автор подачи',
                'verbose_name_plural': 'Авторы подачи',
                'ordering': ['author_order'],
                'unique_together': {('submission', 'author')},
            },
        ),
    ]
