# Generated by Django 5.2.4 on 2025-07-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originality', models.PositiveSmallIntegerField(choices=[(1, '1 - Низкая'), (2, '2 - Ниже среднего'), (3, '3 - Средняя'), (4, '4 - Выше среднего'), (5, '5 - Высокая')], verbose_name='Оригинальность')),
                ('scientific_value', models.PositiveSmallIntegerField(choices=[(1, '1 - Низкая'), (2, '2 - Ниже среднего'), (3, '3 - Средняя'), (4, '4 - Выше среднего'), (5, '5 - Высокая')], verbose_name='Научная ценность')),
                ('methodology', models.PositiveSmallIntegerField(choices=[(1, '1 - Слабая'), (2, '2 - Ниже среднего'), (3, '3 - Средняя'), (4, '4 - Выше среднего'), (5, '5 - Сильная')], verbose_name='Методология')),
                ('presentation', models.PositiveSmallIntegerField(choices=[(1, '1 - Плохая'), (2, '2 - Ниже среднего'), (3, '3 - Средняя'), (4, '4 - Выше среднего'), (5, '5 - Отличная')], verbose_name='Презентация')),
                ('comments_for_author', models.TextField(verbose_name='Комментарии для автора')),
                ('comments_for_editor', models.TextField(blank=True, verbose_name='Комментарии для редактора')),
                ('recommendation', models.CharField(choices=[('accept', 'Принять'), ('minor_revision', 'Незначительные исправления'), ('major_revision', 'Значительные исправления'), ('reject', 'Отклонить')], max_length=20, verbose_name='Рекомендация')),
                ('status', models.CharField(choices=[('assigned', 'Назначена'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='assigned', max_length=15, verbose_name='Статус')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Анонимная рецензия')),
                ('conflict_of_interest', models.BooleanField(default=False, verbose_name='Конфликт интересов')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
                'ordering': ['-created_at'],
            },
        ),
    ]
