# Generated by Django 5.2.7 on 2025-11-02 14:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
        ('submissions', '0003_section_remove_submission_abstract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='annotated_manuscript',
            field=models.FileField(blank=True, null=True, upload_to='reviews/annotated/', verbose_name='Аннотированная рукопись'),
        ),
        migrations.AddField(
            model_name='review',
            name='conflict_details',
            field=models.TextField(blank=True, verbose_name='Детали конфликта интересов'),
        ),
        migrations.AddField(
            model_name='review',
            name='general_comments',
            field=models.TextField(blank=True, verbose_name='Общие комментарии'),
        ),
        migrations.AddField(
            model_name='review',
            name='language_quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Плохое'), (2, '2 - Ниже среднего'), (3, '3 - Среднее'), (4, '4 - Выше среднего'), (5, '5 - Отличное')], null=True, verbose_name='Качество языка'),
        ),
        migrations.AddField(
            model_name='review',
            name='relevance',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Низкая'), (2, '2 - Ниже среднего'), (3, '3 - Средняя'), (4, '4 - Выше среднего'), (5, '5 - Высокая')], null=True, verbose_name='Релевантность'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_file',
            field=models.FileField(blank=True, null=True, upload_to='reviews/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Файл рецензии'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_file_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия рецензируемого файла'),
        ),
        migrations.AddField(
            model_name='review',
            name='revision_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер ревизии'),
        ),
        migrations.AddField(
            model_name='review',
            name='revision_requested',
            field=models.BooleanField(default=False, verbose_name='Требуются исправления'),
        ),
        migrations.AddField(
            model_name='review',
            name='strengths',
            field=models.TextField(blank=True, verbose_name='Сильные стороны'),
        ),
        migrations.AddField(
            model_name='review',
            name='suggestions',
            field=models.TextField(blank=True, verbose_name='Рекомендации по улучшению'),
        ),
        migrations.AddField(
            model_name='review',
            name='time_spent',
            field=models.PositiveIntegerField(blank=True, help_text='Сколько времени рецензент потратил на рецензию', null=True, verbose_name='Потрачено времени (минуты)'),
        ),
        migrations.AddField(
            model_name='review',
            name='visible_to_author',
            field=models.BooleanField(default=True, verbose_name='Видима автору'),
        ),
        migrations.AddField(
            model_name='review',
            name='weaknesses',
            field=models.TextField(blank=True, verbose_name='Слабые стороны'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments_for_author',
            field=models.TextField(blank=True, verbose_name='Комментарии для автора'),
        ),
        migrations.AlterField(
            model_name='review',
            name='methodology',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Слабая'), (2, '2 - Ниже среднего'), (3, '3 - Средняя'), (4, '4 - Выше среднего'), (5, '5 - Сильная')], null=True, verbose_name='Методология'),
        ),
        migrations.AlterField(
            model_name='review',
            name='originality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Низкая'), (2, '2 - Ниже среднего'), (3, '3 - Средняя'), (4, '4 - Выше среднего'), (5, '5 - Высокая')], null=True, verbose_name='Оригинальность'),
        ),
        migrations.AlterField(
            model_name='review',
            name='presentation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Плохая'), (2, '2 - Ниже среднего'), (3, '3 - Средняя'), (4, '4 - Выше среднего'), (5, '5 - Отличная')], null=True, verbose_name='Презентация'),
        ),
        migrations.AlterField(
            model_name='review',
            name='scientific_value',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Низкая'), (2, '2 - Ниже среднего'), (3, '3 - Средняя'), (4, '4 - Выше среднего'), (5, '5 - Высокая')], null=True, verbose_name='Научная ценность'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('submission', 'reviewer', 'revision_number')},
        ),
        migrations.CreateModel(
            name='EditorialDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accept', 'Принять'), ('revision_minor', 'Требуются незначительные исправления'), ('revision_major', 'Требуются значительные исправления'), ('resubmit', 'Пересмотреть и отправить заново'), ('reject', 'Отклонить'), ('decline', 'Отозвать')], max_length=20, verbose_name='Решение')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('comments_for_author', models.TextField(blank=True, verbose_name='Комментарии для автора')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальное решение')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата решения')),
                ('decision_maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Принял решение')),
                ('reviews', models.ManyToManyField(blank=True, related_name='decisions', to='reviews.review', verbose_name='Учтенные рецензии')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_decisions', to='submissions.submission', verbose_name='Подача')),
            ],
            options={
                'verbose_name': 'Редакторское решение',
                'verbose_name_plural': 'Редакторские решения',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принята'), ('declined', 'Отклонена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=15, verbose_name='Статус')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('response_due', models.DateTimeField(blank=True, null=True, verbose_name='Срок ответа')),
                ('review_due', models.DateTimeField(blank=True, null=True, verbose_name='Срок рецензии')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('invitation_message', models.TextField(blank=True, verbose_name='Пригласительное сообщение')),
                ('decline_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('can_view_identity', models.BooleanField(default=False, help_text='Для открытого рецензирования', verbose_name='Может видеть авторов')),
                ('is_blind', models.BooleanField(default=True, help_text='Рецензент не видит авторов', verbose_name='Слепое рецензирование')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('review', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_assignment', to='reviews.review', verbose_name='Рецензия')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Рецензент')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='submissions.submission', verbose_name='Подача')),
            ],
            options={
                'verbose_name': 'Назначение рецензента',
                'verbose_name_plural': 'Назначения рецензентов',
                'ordering': ['-assigned_at'],
                'unique_together': {('submission', 'reviewer')},
            },
        ),
        migrations.AddField(
            model_name='review',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_obj', to='reviews.reviewassignment', verbose_name='Назначение'),
        ),
    ]
